#!/bin/sh

exec 2>&1
# LD_PRELOAD=$RUBY_ALLOCATOR HOME=/home/discourse USER=discourse exec thpoff chpst -u discourse:www-data -U discourse:www-data bundle exec config/unicorn_launcher -E production -c config/unicorn.conf.rb

cd ${HAB_DISCOURSE_PATH}
exec bundle exec config/unicorn_launcher -E {{cfg.environment}} -c config/unicorn.conf.rb
